### ISSUE TITLE
Incomplete formatting and missing words

### ISSUE THREAD

**Issue by JonTheNiceGuy** [ministryofjustice/technical-guidance#35]
Not sure exactly whether this is intentional, but on [technical-guidance/principles/development-principles.md](https://github.com/ministryofjustice/technical-guidance/blob/master/principles/development-principles.md) there are a lot of errors in both formatting and missing words, for example, there is this:

```Markdown
### 1. Share the knowledge
If you have knowledge which is unique to you, it is your responsibility to share it.
We follow “[github flow](https://guides.github.com/introduction/flow/)”, to keep branches small and short-lived, and ensure knowledge is shared.
If you produce something reusable, package it (e.g. with pypi or rubygems) & share it with others on [MoJ Reuseables]( https://github.com/ministryofjustice/moj-reusables)
All non-throwaway code should be reviewed - no-one is 100% right, 
100% of the time… be aware that ‘throwaway’ code has a nasty habit of

### 2. Code should be correct, clear, concise - in that order
```

When you get to point 4, you've started prefixing lines with *'s to get bullets. And, what is happening with the "'throwaway' code" line?

**Comment by aliuk2012** [comment]
Hi @JonTheNiceGuy, thanks for raising this issue with the guidance. I'll try to rectify this issue over the next couple of days.

**Comment by AntonyBishop** [comment]
Aged-out
