### ISSUE TITLE
Update out of hours support guidance to advise on what level of seniority staff on call should be

### ISSUE THREAD

**Issue by SteveMarshall** [ministryofjustice/technical-guidance#59]
As @tocacar says in #55:

> Also, perhaps we need to include a statement on which level of staff is acceptable to be on call, which is possibly where things become tricky. My feeling is that senior and mid level developers can be on call, however, probably not two mid levels. It's probably infeasible to require a senior to be on call. I'm interested to hear thoughts here. I feel a junior can a secondary and should experience on call, but possibly not if a mid-level is primary? I suppose decisions will need to be made pragmatically on a team by team basis, but some guidance will probably be useful.

**Comment by AntonyBishop** [comment]
Aged-out
