### ISSUE TITLE
Fix relative links so they work when published

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/technical-guidance#63]
Some relative links work in local development mode, but compile incorrectly when the site is published. (e.g. #62)

**Comment by joelgsamuel** [comment]
https://github.com/ministryofjustice/technical-guidance/blame/master/standards/documenting-infrastructure-owners.md#L34 is another example

**Comment by digitalronin** [comment]
@joelgsamuel https://github.com/ministryofjustice/technical-guidance/pull/66
