### ISSUE TITLE
Broken runbook link in 'Documenting owners of Infrastructure'

### ISSUE THREAD

**Issue by pc1334** [ministryofjustice/technical-guidance#65]
The `the service's runbook` link on https://ministryofjustice.github.io/technical-guidance/standards/documenting-infrastructure-owners/#mandatory is broken - looks like the `technical-guidance` part of the link is missing in the path.

Could be a dupe/symptom of #63

**Comment by digitalronin** [comment]
fixed by #66

**Comment by pc1334** [comment]
Awesome, thanks 😀
