### ISSUE TITLE
Bug on Safari 13 / Chrome (iOS)

### ISSUE THREAD

**Issue by andy-gg** [ministryofjustice/technical-guidance#87]
In Safari and Chrome on the latest iOS (13), it appears the last bullet point of each `<ul>` is not clickable.

For example, on Safari on an iPhone go to: 
https://ministryofjustice.github.io/technical-guidance

Try to click on: 
"Frontend Development Principles"

FYI - a similar bug was found and fixed with Security Guidance - https://github.com/ministryofjustice/security-guidance/issues/53

**Comment by AntonyBishop** [comment]
Aged-out
